# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title:            Aspire Themes
description:      Elegant WordPress and Ghost Themes
url:              https://aspirethemes.com
disqus:           aspirethemes
email:            aspirethemes@gmail.com
mailto:           mailto:aspirethemes@gmail.com
twitter:          http://www.twitter.com/aspirethemes
medium:           https://medium.com/aspirethemes
dribbble:         https://dribbble.com/aspirethemes
github:           https://github.com/aspirethemes
facebook:         https://www.facebook.com/aspirethemes
themeforest:      http://themeforest.net/user/aspirethemes
creative_market:  https://creativemarket.com/aspirethemes
upwork:           https://www.upwork.com/freelancers/~01b8a143dfeba1b95a

permalink: /blog/:title
post_dirs: false
markdown: kramdown

include:
  - _pages

gems:
  - jekyll-sitemap
  - jekyll/tagging

tag_page_dir:        tag
tag_page_layout:     tag_page
tag_permalink_style: pretty

sass:
  style: compressed

collections:
  themes:
    output: true
    permalink: /themes/:path/
  docs:
    output: true
    permalink: /docs/:path/