# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Aspire Themes
description:      Elegant WordPress and Ghost Themes
baseurl:          ''
url:              http://aspirethemes.com
disqus:           aspirethemes
email:            aspirethemes@gmail.com
mailto:           mailto:aspirethemes@gmail.com
twitter:          http://www.twitter.com/aspirethemes
github:           https://github.com/aspirethemes
facebook:         https://www.facebook.com/aspirethemes
themeforest:      http://themeforest.net/user/aspirethemes
creative_market:  https://creativemarket.com/aspirethemes

# Build settings
markdown: kramdown

include:
  - _pages

gems:
  - jekyll-sitemap

permalink: none
post_dirs: false

# Testimonials
testimonials:
  - testimonial: I really liked the design! The designer answered my questions before purchase, and after the purchasing was superb. I am happy with the purchase!
    author:      Juan Alejandro Oliva

  - testimonial: A simple, clean theme. After sales support is excellent! Thanks Ahmad for your quick and helpful replies. Aspire Themes are a credit to the theme industry.
    author:      Patrick Layley

  - testimonial: A great Ghost theme! Simple, elegant, lots of post choices on the home page, just what I wanted. It was mostly easy to setup, but when I had a question, the support was fantastic. TY!!
    author:      Glenn Zucman

  - testimonial: Outstanding & quick support from Ahmad! & beautiful theme.
    author:      Phalgun Raju - CEO of expertDB