# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title:              Aspire Themes
description:        Elegant WordPress, Ghost & Jekyll Themes
url:                https://aspirethemes.com
disqus:             aspirethemes
email:              aspirethemes@gmail.com
mailto:             mailto:aspirethemes@gmail.com
twitter_url:        https://twitter.com/aspirethemes
medium_url:         https://medium.com/aspirethemes
github_url:         https://github.com/aspirethemes
facebook_url:       https://www.facebook.com/aspirethemes
themeforest_url:    https://themeforest.net/user/aspirethemes/portfolio?ref=aspirethemes
creativemarket_url: https://creativemarket.com/aspirethemes

permalink: /blog/:title
post_dirs: false
markdown: kramdown

include:
  - _pages

sass:
  style: compressed

collections:
  themes:
    output: true
    permalink: /themes/:path/
  preview:
    output: true
    permalink: /preview/:path/
  docs:
    output: true
    permalink: /docs/:path/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging

# Jekyll Tagging
tag_page_dir:        tag
tag_page_layout:     tag_page
tag_permalink_style: pretty

# Jekyll SEO Tag
twitter:
  username: aspirethemes

social:
  links:
    - http://www.twitter.com/aspirethemes
    - https://medium.com/aspirethemes
    - https://github.com/aspirethemes
    - https://www.facebook.com/aspirethemes
    - https://themeforest.net/user/aspirethemes
    - https://creativemarket.com/aspirethemes